### ISSUE TITLE
Consider giving an option to extend the height of each list?

### ISSUE THREAD

**Issue by johnconnor0324** [sudonatalie/layout-trello#13]
I think the height of each list can be slightly taller: it would show more information in a more effective way. Thank you for the great work though! Such a bliss not having to scroll left/right to the edge of the world.

**Comment by natalieperna** [comment]
Good suggestion, but I don't have a page for options right now and probably won't be adding one. (I'm behind as it is on basic maintenance, especially since I'm not using the extension much anymore.)

However, this is a pretty easy code change if you want to clone the extension and modify your own copy. I don't know your experience level, so detailed instructions follow:

1. Go to https://github.com/natalieperna/layout-trello.
2. Click Download ZIP.
3. Extract it somewhere.
4. Open chrome://extensions/.
5. Check off "Developer Mode".
6. Click "Load unpacked extension..."
7. Navigate to and select the unzipped `layout-trello` directory.
8. Open `css/layout.css` with your favourite text editor.
9. On line 26, edit `40vh` to whatever you want (`40vh` is 40% of the height of the viewport, so you might want `60vh`).
10. Enjoy taller boards?

**Comment by sudonatalie** [comment]
No longer considering this feature.

**Comment by Dlafko** [comment]
Thanks that worked but it overlaps the bottom row  how do I get the bottom row to move down
