### ISSUE TITLE
Release for Firefox

### ISSUE THREAD

**Issue by hardpenguin** [sudonatalie/layout-trello#49]
Hi @sudonatalie!

I think that your addon would be really useful in my daily workflow so I would like to ask you for a Firefox release on [Firefox Add-ons](https://addons.mozilla.org/) aka AMO.

I believe that the user @Gwened has already solved the issue of compatibility in their [fork](https://github.com/Gwened/tredolist), specifically [this commit](https://github.com/Gwened/tredolist/commit/f57511dc37f0e2a575470786eb44011687d2a3a3).

Looks like the only required change was to add the following object

```
"applications": {
     "gecko": {
       "id": "<developer email here>"
     }
   }
```

to `manifest.json` due to [this requirement by Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_add-on_ID).

The [packaging process is pretty much the same as in Chrome](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_).

The addon already installs perfectly in [debugging, temporary mode in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox), there is only one problem. The addon has to be [signed by Mozilla for it to be installable by regular users](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution) in the release version of the Firefox.

Would you sign and release the addon in AMO under your own name? Thanks in advance!

**Comment by Gwened** [comment]
Hi, indeed it works almost out of the box (unlike the port for Microsoft Edge).
If you wanna check out, my fork is available for Firefox here: https://addons.mozilla.org/en-US/firefox/addon/tredolist/

**Comment by sudonatalie** [comment]
I don't currently have any plans to release it on other platforms, mostly because I don't want to contribute much time to maintaining this and releasing on additional platforms multiplies the opportunities for potential future breakage.

That being said, I (and [the license](https://github.com/sudonatalie/layout-trello/blob/master/LICENSE)) have no problem with you or someone else releasing it elsewhere. You could fork it, or if there's just a small manifest addition that doesn't break it on Chrome, I'd be happy to accept it as a PR.

Glad to hear the extension's providing value for you!
